#!/usr/bin/env python3

import os.path
import shlex
import subprocess
from configparser import ConfigParser
from pathlib import Path


def main():
    config = ConfigParser()
    config_file = Path(os.path.expandvars("$XDG_CONFIG_HOME")) / "cryptfs.conf"
    config.read(config_file)

    backrest = config["backrest"]
    command = "gocryptfs %(location)s %(mount)s" % backrest
    subprocess.run(shlex.split(command), input=backrest["password"], text=True)


if __name__ == "__main__":
    main()
